export interface BlogPost {
  id: string;
  title: string;
  slug: string;
  category: string;
  sport: string;
  author: string;
  authorAvatar: string;
  authorRole: string;
  date: string;
  readTime: number;
  image: string;
  excerpt: string;
  content: BlogSection[];
  tags: string[];
  featured: boolean;
}

export interface BlogSection {
  type: "heading" | "paragraph" | "list" | "tip" | "quote";
  text?: string;
  items?: string[];
}

export const blogPosts: BlogPost[] = [
  {
    id: "b1",
    title: "5 Bài Tập Chạy Bộ Giúp Tăng Tốc Độ Hiệu Quả",
    slug: "bai-tap-chay-bo-tang-toc-do",
    category: "Huấn luyện",
    sport: "Chạy bộ",
    author: "HLV Trần Minh Khoa",
    authorAvatar: "MK",
    authorRole: "Huấn luyện viên Marathon",
    date: "28/03/2026",
    readTime: 6,
    image: "https://images.unsplash.com/photo-1662651800883-b784f138e9dd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxydW5uaW5nJTIwdHJhaW5pbmclMjB0aXBzJTIwYXRobGV0ZXxlbnwxfHx8fDE3NzQ5MzI5MjB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Khám phá 5 bài tập chạy bộ chuyên nghiệp giúp bạn cải thiện tốc độ, sức bền và kỹ thuật chạy một cách hiệu quả nhất.",
    tags: ["chạy bộ", "tốc độ", "huấn luyện", "kỹ thuật"],
    featured: true,
    content: [
      { type: "paragraph", text: "Chạy bộ không chỉ đơn giản là đặt một chân trước chân kia. Để thực sự cải thiện tốc độ và hiệu suất, bạn cần áp dụng các bài tập chuyên biệt được thiết kế bởi các chuyên gia hàng đầu." },
      { type: "heading", text: "1. Interval Training (Chạy ngắt quãng)" },
      { type: "paragraph", text: "Đây là phương pháp huấn luyện hiệu quả nhất để tăng tốc độ. Bạn xen kẽ giữa các đoạn chạy nhanh hết sức và các đoạn nghỉ ngơi nhẹ nhàng." },
      { type: "list", items: ["Khởi động 10 phút với nhịp độ nhẹ", "Chạy nhanh 400m (80-90% sức lực)", "Đi bộ hoặc chạy nhẹ 200m để hồi phục", "Lặp lại 6-8 lần", "Thư giãn 10 phút"] },
      { type: "tip", text: "💡 Mẹo pro: Dùng đồng hồ GPS để theo dõi nhịp tim và tốc độ chính xác. Nhịp tim trong giai đoạn nước rút nên đạt 85-95% nhịp tim tối đa." },
      { type: "heading", text: "2. Tempo Run (Chạy nhịp)" },
      { type: "paragraph", text: "Tempo run là chạy ở tốc độ 'không thoải mái nhưng có thể duy trì được' trong khoảng 20-40 phút. Đây là ngưỡng lactate - nơi cơ thể bắt đầu tích tụ axit lactic." },
      { type: "heading", text: "3. Hill Repeats (Chạy đồi lặp)" },
      { type: "paragraph", text: "Chạy lên dốc xây dựng sức mạnh cho cơ chân, đặc biệt là cơ mông, đùi sau và bắp chân. Mỗi tuần thực hiện 1-2 buổi chạy đồi." },
      { type: "heading", text: "4. Fartlek Training" },
      { type: "paragraph", text: "Fartlek (tiếng Thụy Điển có nghĩa là 'chơi tốc độ') là hình thức chạy không có cấu trúc cố định. Bạn tự do thay đổi tốc độ theo cảm hứng trong suốt buổi chạy." },
      { type: "heading", text: "5. Strides (Chạy nước rút ngắn)" },
      { type: "paragraph", text: "Strides là các đoạn chạy nhanh dần từ 70% lên 95% tốc độ tối đa trong khoảng 20-30 giây, sau đó giảm dần về tốc độ chạy bình thường. Thực hiện 4-6 strides sau buổi chạy dễ." },
      { type: "quote", text: "\"Tốc độ không đến từ việc cố gắng chạy nhanh hơn mỗi ngày, mà đến từ sự nhất quán trong huấn luyện có hệ thống.\" - HLV Trần Minh Khoa" },
    ],
  },
  {
    id: "b2",
    title: "Hướng Dẫn Tập Gym Cho Người Mới Bắt Đầu Từ A-Z",
    slug: "tap-gym-cho-nguoi-moi-bat-dau",
    category: "Gym & Fitness",
    sport: "Gym & Fitness",
    author: "PT Nguyễn Thanh Hùng",
    authorAvatar: "TH",
    authorRole: "Personal Trainer ISSA Certified",
    date: "25/03/2026",
    readTime: 8,
    image: "https://images.unsplash.com/photo-1584827386916-b5351d3ba34b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxneW0lMjB3b3Jrb3V0JTIwZml0bmVzcyUyMGV4ZXJjaXNlfGVufDF8fHx8MTc3NDkzMjkyMXww&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Lộ trình tập gym hoàn chỉnh dành cho người mới: từ khởi động, các bài tập cơ bản, đến dinh dưỡng và phục hồi sau tập.",
    tags: ["gym", "người mới", "tập luyện", "cơ bắp"],
    featured: true,
    content: [
      { type: "paragraph", text: "Bước vào phòng gym lần đầu tiên có thể khiến bạn choáng ngợp. Máy móc phức tạp, người xung quanh ai cũng có vẻ biết mình đang làm gì - trong khi bạn thì không. Đừng lo lắng! Bài viết này sẽ giúp bạn." },
      { type: "heading", text: "Tuần 1-2: Xây nền tảng" },
      { type: "paragraph", text: "Hai tuần đầu tiên tập trung vào việc học đúng kỹ thuật các bài tập cơ bản. Đừng vội vàng tăng tạ - hãy đảm bảo form (tư thế) chính xác trước." },
      { type: "list", items: ["Squat - Ngồi xổm với tạ đòn hoặc không tạ", "Deadlift - Kéo tạ từ sàn lên", "Bench Press - Đẩy tạ trên ghế phẳng", "Overhead Press - Đẩy tạ trên đầu", "Pull-up / Lat Pulldown - Kéo xà hoặc cáp lưng"] },
      { type: "tip", text: "💡 Bắt đầu với tạ nhẹ hơn bạn nghĩ. Mục tiêu tuần 1-2 là cảm nhận cơ bắp hoạt động đúng cách, không phải nhấc nặng." },
      { type: "heading", text: "Lịch tập cho người mới (3 buổi/tuần)" },
      { type: "list", items: ["Thứ 2: Ngực + Vai + Tay sau (Push)", "Thứ 4: Lưng + Tay trước (Pull)", "Thứ 6: Chân + Mông (Legs)", "Thứ 3, 5, 7: Nghỉ ngơi hoặc cardio nhẹ"] },
      { type: "heading", text: "Dinh dưỡng khi tập gym" },
      { type: "paragraph", text: "Tập gym mà không ăn đúng cách thì kết quả sẽ rất hạn chế. Protein là yếu tố quan trọng nhất để xây dựng và phục hồi cơ bắp." },
      { type: "list", items: ["Protein: 1.6-2.2g/kg cân nặng mỗi ngày", "Carb: 3-5g/kg cân nặng (nguồn năng lượng chính)", "Fat: 0.8-1.2g/kg cân nặng (hormone và tế bào)", "Nước: Tối thiểu 2-3 lít mỗi ngày"] },
      { type: "quote", text: "\"Cơ bắp được tạo ra trong bếp, không phải trong phòng gym.\" - Nguyên tắc vàng của giới fitness" },
    ],
  },
  {
    id: "b3",
    title: "Kỹ Thuật Đá Bóng Chuẩn: Từ Dẫn Bóng Đến Sút Cầu Môn",
    slug: "ky-thuat-da-bong-chuan",
    category: "Kỹ thuật",
    sport: "Bóng đá",
    author: "HLV Phạm Văn Đức",
    authorAvatar: "VĐ",
    authorRole: "Cựu cầu thủ V.League",
    date: "22/03/2026",
    readTime: 7,
    image: "https://images.unsplash.com/photo-1771257807779-a72e74deaa11?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMHNvY2NlciUyMHRyYWluaW5nfGVufDF8fHx8MTc3NDkzMjkyMXww&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Những kỹ thuật cơ bản và nâng cao trong bóng đá mà mọi cầu thủ cần nắm vững, từ dẫn bóng, chuyền bóng cho đến kỹ thuật sút cầu môn.",
    tags: ["bóng đá", "kỹ thuật", "sút bóng", "dẫn bóng"],
    featured: false,
    content: [
      { type: "paragraph", text: "Bóng đá là môn thể thao của kỹ năng và chiến thuật. Dù bạn đang chơi ở sân phủi hay muốn tiến xa hơn, việc nắm vững kỹ thuật cơ bản là nền tảng không thể thiếu." },
      { type: "heading", text: "1. Kỹ thuật dẫn bóng (Dribbling)" },
      { type: "paragraph", text: "Dẫn bóng tốt nghĩa là giữ bóng gần chân, dưới sự kiểm soát hoàn toàn, trong khi vẫn có thể quan sát xung quanh." },
      { type: "list", items: ["Sử dụng bề mặt trong và ngoài của bàn chân", "Giữ đầu ngẩng cao để quan sát", "Bước ngắn và nhịp nhàng khi có đối thủ", "Thay đổi hướng đột ngột để qua người"] },
      { type: "heading", text: "2. Kỹ thuật chuyền bóng (Passing)" },
      { type: "paragraph", text: "Chuyền bóng chính xác là nền tảng của lối chơi tập thể. 70% thành công của một đội phụ thuộc vào chất lượng chuyền bóng." },
      { type: "tip", text: "💡 Khi chuyền bóng, hướng bàn chân chống về phía muốn chuyền. Dùng lòng bàn chân để chuyền ngắn, mu bàn chân cho đường chuyền dài." },
      { type: "heading", text: "3. Kỹ thuật sút cầu môn" },
      { type: "paragraph", text: "Sút bóng là kỹ năng được mơ ước nhất nhưng cũng khó nhất. Có nhiều kỹ thuật khác nhau tùy tình huống." },
      { type: "list", items: ["Sút bằng mu bàn chân: Tạo lực mạnh nhất", "Sút bằng lòng bàn chân: Chính xác nhất", "Sút đầu gối: Trong vòng cấm khi không có không gian", "Sút vô-lê: Bắt bóng trên không trước khi chạm đất"] },
      { type: "quote", text: "\"Kỹ thuật là thứ bạn luyện tập 10,000 giờ. Sau đó, nó trở thành bản năng.\" - HLV Phạm Văn Đức" },
    ],
  },
  {
    id: "b4",
    title: "Yoga Cho Vận Động Viên: Tăng Linh Hoạt và Phục Hồi",
    slug: "yoga-cho-van-dong-vien",
    category: "Phục hồi",
    sport: "Yoga",
    author: "HLV Lê Thị Mai",
    authorAvatar: "LM",
    authorRole: "Giáo viên Yoga RYT-500",
    date: "20/03/2026",
    readTime: 5,
    image: "https://images.unsplash.com/photo-1635545999375-057ee4013deb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b2dhJTIwbWVkaXRhdGlvbiUyMHdlbGxuZXNzfGVufDF8fHx8MTc3NDkxODk1M3ww&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Yoga không chỉ dành cho phụ nữ hay người cao tuổi. Khám phá cách yoga có thể giúp vận động viên mọi môn thể thao cải thiện hiệu suất và phục hồi nhanh hơn.",
    tags: ["yoga", "linh hoạt", "phục hồi", "thể thao"],
    featured: false,
    content: [
      { type: "paragraph", text: "Ngày càng nhiều vận động viên chuyên nghiệp - từ cầu thủ bóng đá đến võ sĩ MMA - tích hợp yoga vào chương trình tập luyện của họ. Lý do đơn giản: yoga hiệu quả." },
      { type: "heading", text: "Tại sao vận động viên cần yoga?" },
      { type: "list", items: ["Tăng biên độ vận động khớp", "Giảm nguy cơ chấn thương", "Cải thiện khả năng thăng bằng và phối hợp", "Phục hồi cơ bắp nhanh hơn sau tập luyện nặng", "Cải thiện tập trung và kiểm soát hơi thở"] },
      { type: "heading", text: "5 tư thế yoga tốt nhất cho vận động viên" },
      { type: "list", items: ["Pigeon Pose: Mở hông, kéo giãn cơ mông - tốt cho runner và cyclist", "Downward Dog: Kéo giãn chuỗi cơ sau - toàn thân", "Warrior I & II: Tăng sức mạnh chân và vai", "Triangle Pose: Kéo giãn hông, đùi trong và cột sống", "Child's Pose: Phục hồi lưng dưới và hông"] },
      { type: "tip", text: "💡 Thực hiện yoga vào buổi tối sau khi tập luyện, hoặc vào ngày nghỉ. Đừng cố ép cơ thể vào các tư thế khó khi cơ còn lạnh." },
      { type: "quote", text: "\"Sức mạnh không đến từ việc có thể làm điều gì đó, mà đến từ việc vượt qua những điều bạn nghĩ mình không thể làm.\" - Rickson Gracie" },
    ],
  },
  {
    id: "b5",
    title: "Dinh Dưỡng Thể Thao: Ăn Gì Để Tập Luyện Hiệu Quả Hơn",
    slug: "dinh-duong-the-thao",
    category: "Dinh dưỡng",
    sport: "Đa môn",
    author: "Chuyên gia Võ Thị Lan",
    authorAvatar: "VL",
    authorRole: "Chuyên gia Dinh dưỡng Thể thao",
    date: "18/03/2026",
    readTime: 9,
    image: "https://images.unsplash.com/photo-1774557937569-93b4a6e358a3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcG9ydHMlMjBudXRyaXRpb24lMjBoZWFsdGh5JTIwZm9vZCUyMGF0aGxldGV8ZW58MXx8fHwxNzc0OTMyOTIyfDA&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Dinh dưỡng đúng cách là chìa khóa để tối ưu hóa hiệu suất thể thao. Tìm hiểu những gì nên ăn trước, trong và sau khi tập luyện.",
    tags: ["dinh dưỡng", "protein", "carb", "phục hồi"],
    featured: true,
    content: [
      { type: "paragraph", text: "Bạn có thể tập luyện chăm chỉ nhất thế giới, nhưng nếu không ăn đúng cách, kết quả sẽ rất hạn chế. Dinh dưỡng thể thao là khoa học về việc nuôi dưỡng cơ thể để đạt hiệu suất cao nhất." },
      { type: "heading", text: "Bữa ăn trước tập (2-3 giờ trước)" },
      { type: "paragraph", text: "Bữa ăn trước tập cần cung cấp đủ năng lượng mà không khiến dạ dày khó chịu. Tập trung vào carbohydrate phức hợp và protein vừa phải." },
      { type: "list", items: ["Cơm + ức gà + rau xanh", "Bánh mì nguyên cám + trứng + bơ đậu phộng", "Khoai lang + cá hồi + salad", "Tránh thực phẩm nhiều dầu mỡ và chất xơ cao trước tập"] },
      { type: "heading", text: "Dinh dưỡng trong khi tập (cho buổi tập > 60 phút)" },
      { type: "list", items: ["Uống 150-250ml nước mỗi 15-20 phút", "Với buổi tập > 90 phút: bổ sung 30-60g carb/giờ", "Gel năng lượng, chuối, nước trái cây pha loãng"] },
      { type: "heading", text: "Bữa ăn phục hồi sau tập (trong 30-60 phút)" },
      { type: "paragraph", text: "Đây là 'cửa sổ vàng' để phục hồi. Cơ thể hấp thụ dinh dưỡng hiệu quả nhất trong 30-60 phút đầu sau tập." },
      { type: "list", items: ["Protein: 20-40g (whey protein, trứng, sữa chua Hy Lạp)", "Carb: 0.8-1.2g/kg cân nặng để nạp lại glycogen", "Tỷ lệ Carb:Protein lý tưởng = 3:1 hoặc 4:1"] },
      { type: "tip", text: "💡 Sinh tố phục hồi nhanh: 1 quả chuối + 200ml sữa tươi + 1 muỗng protein + 1 muỗng mật ong. Đơn giản, ngon và hiệu quả!" },
      { type: "quote", text: "\"Ăn để sống, không phải sống để ăn - nhưng với vận động viên, ăn đúng cách chính là sống tốt hơn.\" - Chuyên gia Võ Thị Lan" },
    ],
  },
  {
    id: "b6",
    title: "Bơi Lội Đúng Kỹ Thuật: Cải Thiện Sải Tay và Nhịp Thở",
    slug: "boi-loi-dung-ky-thuat",
    category: "Kỹ thuật",
    sport: "Bơi lội",
    author: "VĐV Hoàng Minh Đức",
    authorAvatar: "MĐ",
    authorRole: "Vô địch Bơi lội Quốc gia",
    date: "15/03/2026",
    readTime: 6,
    image: "https://images.unsplash.com/photo-1768576544627-c0a7149d0c5b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzd2ltbWluZyUyMHBvb2wlMjB0cmFpbmluZyUyMHRlY2huaXF1ZXxlbnwxfHx8fDE3NzQ5MzI5MjN8MA&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Kỹ thuật bơi đúng cách giúp bạn bơi xa hơn, nhanh hơn và ít mệt hơn. Hướng dẫn chi tiết về sải tay, đập chân và nhịp thở trong bơi tự do.",
    tags: ["bơi lội", "kỹ thuật", "freestyle", "nhịp thở"],
    featured: false,
    content: [
      { type: "paragraph", text: "Bơi lội là môn thể thao toàn thân tuyệt vời, tốt cho tim mạch và không gây áp lực lên khớp. Nhưng bơi sai kỹ thuật không chỉ làm bạn chậm hơn mà còn dễ bị chấn thương vai." },
      { type: "heading", text: "Tư thế thân người (Body Position)" },
      { type: "paragraph", text: "Tư thế ngang và thẳng trong nước là nền tảng. Cơ thể phải nằm ngang mặt nước, không để hông chìm xuống - điều này tạo ra lực cản lớn." },
      { type: "heading", text: "Kỹ thuật sải tay bơi tự do" },
      { type: "list", items: ["Entry: Tay vào nước tại vị trí 11 giờ và 1 giờ (không qua đường giữa)", "Catch: 'Bắt nước' - cẳng tay thẳng đứng xuống dưới", "Pull: Kéo tay theo đường S ngắn dưới thân", "Push: Đẩy nước về phía sau cho đến khi tay duỗi thẳng", "Recovery: Khuỷu tay lên cao, thư giãn"] },
      { type: "tip", text: "💡 Hãy thực hành từng giai đoạn của sải tay đứng yên tại bờ hồ trước khi áp dụng dưới nước. Cơ não cần thời gian học tư thế mới." },
      { type: "heading", text: "Kỹ thuật nhịp thở" },
      { type: "paragraph", text: "Nhịp thở sai là nguyên nhân #1 khiến người mới bơi nhanh mệt. Thở về một bên mỗi 2 nhịp đập tay (beginner) hoặc thở hai bên mỗi 3 nhịp (advanced)." },
    ],
  },
  {
    id: "b7",
    title: "Đạp Xe Đường Trường: Hướng Dẫn Cho Người Mới",
    slug: "dap-xe-duong-truong-nguoi-moi",
    category: "Huấn luyện",
    sport: "Xe đạp",
    author: "HLV Bùi Công Danh",
    authorAvatar: "CD",
    authorRole: "Huấn luyện viên Cycling",
    date: "12/03/2026",
    readTime: 7,
    image: "https://images.unsplash.com/photo-1772439783106-dff24711a71b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjeWNsaW5nJTIwcm9hZCUyMGJpa2UlMjBvdXRkb29yfGVufDF8fHx8MTc3NDkzMjkyM3ww&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Bắt đầu hành trình đạp xe đường trường với đúng trang bị, kỹ thuật và kế hoạch tập luyện. Tất cả những gì bạn cần biết trong một bài viết.",
    tags: ["xe đạp", "cycling", "đường trường", "người mới"],
    featured: false,
    content: [
      { type: "paragraph", text: "Đạp xe đường trường đang ngày càng phổ biến tại Việt Nam. Từ những cung đường ven biển Đà Nẵng đến những con đèo hùng vĩ Tây Bắc, cycling mang lại trải nghiệm tuyệt vời." },
      { type: "heading", text: "Chọn xe đúng cách" },
      { type: "paragraph", text: "Kích thước khung xe (frame size) quyết định 80% sự thoải mái khi đạp. Đo chiều cao và chiều dài chân để xác định size phù hợp." },
      { type: "list", items: ["160-165cm: Frame size XS (47-49cm)", "165-172cm: Frame size S (50-52cm)", "172-180cm: Frame size M (54-56cm)", "180-188cm: Frame size L (57-59cm)"] },
      { type: "heading", text: "Setup xe đúng vị trí (Bike Fit)" },
      { type: "list", items: ["Yên xe: Khi đạp ở điểm thấp nhất, đầu gối gần thẳng (không thẳng hoàn toàn)", "Tay lái: Không quá xa, không quá gần - khuỷu tay hơi cong", "Cleats (nếu dùng): Điều chỉnh để không đau gối"] },
      { type: "tip", text: "💡 Tuần đầu tiên: Đừng đạp hơn 30km/buổi. Cơ thể cần thích nghi với tư thế mới. Nhiều người mới quá hăng hái dẫn đến đau lưng và đầu gối." },
    ],
  },
  {
    id: "b8",
    title: "Cầu Lông Nghiệp Dư: 7 Lỗi Kỹ Thuật Thường Gặp và Cách Sửa",
    slug: "cau-long-7-loi-thuong-gap",
    category: "Kỹ thuật",
    sport: "Cầu lông",
    author: "HLV Dương Quốc Huy",
    authorAvatar: "QH",
    authorRole: "HLV Cầu lông Quốc gia",
    date: "10/03/2026",
    readTime: 5,
    image: "https://images.unsplash.com/photo-1613918431551-b2ef2720387c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWRtaW50b24lMjBjb3VydCUyMHBsYXllcnxlbnwxfHx8fDE3NzQ5MzI5MjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Những lỗi kỹ thuật phổ biến nhất trong cầu lông nghiệp dư và hướng dẫn chi tiết cách khắc phục để nâng cao level chơi của bạn.",
    tags: ["cầu lông", "kỹ thuật", "lỗi cơ bản", "vợt"],
    featured: false,
    content: [
      { type: "paragraph", text: "Sau nhiều năm huấn luyện, tôi nhận ra rằng hầu hết người chơi cầu lông nghiệp dư đều mắc chung những lỗi kỹ thuật. Tin tốt là: tất cả đều có thể sửa được." },
      { type: "heading", text: "Lỗi #1: Cầm vợt sai" },
      { type: "paragraph", text: "Cầm vợt kiểu 'bắt tay' (handshake grip) là cơ bản nhất. Nhiều người cầm vợt quá chặt hoặc để ngón cái không đúng vị trí, dẫn đến giảm sức mạnh và tốc độ đánh." },
      { type: "heading", text: "Lỗi #2: Không di chuyển chân" },
      { type: "paragraph", text: "Cầu lông là môn 70% là di chuyển chân. Nhiều người đứng yên và với tay để đánh thay vì di chuyển đến vị trí tốt." },
      { type: "heading", text: "Lỗi #3: Đánh bằng tay, không phải cổ tay" },
      { type: "paragraph", text: "Sức mạnh trong cầu lông đến từ cú snap cổ tay ở thời điểm tiếp xúc, không phải từ cánh tay toàn phần. Đây là sự khác biệt giữa cú đập 200km/h và 100km/h." },
      { type: "list", items: ["Lỗi #4: Không có preparation (chuẩn bị)", "Lỗi #5: Tư thế serve sai", "Lỗi #6: Drop shot quá cứng", "Lỗi #7: Không theo dõi cầu đến tận cùng"] },
      { type: "tip", text: "💡 Video hóa buổi tập của bạn. Nhìn lại video sẽ giúp bạn nhận ra lỗi nhanh gấp 10 lần so với chỉ cảm nhận." },
    ],
  },
];

export const blogCategories = [
  { id: "all", name: "Tất cả", icon: "📚" },
  { id: "Huấn luyện", name: "Huấn luyện", icon: "🏋️" },
  { id: "Kỹ thuật", name: "Kỹ thuật", icon: "🎯" },
  { id: "Dinh dưỡng", name: "Dinh dưỡng", icon: "🥗" },
  { id: "Phục hồi", name: "Phục hồi", icon: "💆" },
  { id: "Gym & Fitness", name: "Gym & Fitness", icon: "💪" },
];
