export interface Review {
  id: string;
  author: string;
  avatar: string;
  rating: number;
  date: string;
  comment: string;
  verified: boolean;
}

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  sport: string;
  price: number;
  originalPrice: number;
  image: string;
  images: string[];
  rating: number;
  reviewCount: number;
  shortDescription: string;
  description: string;
  specs: Record<string, string>;
  sizes: string[];
  colors: { name: string; hex: string }[];
  inStock: boolean;
  isNew: boolean;
  isBestSeller: boolean;
  isOnSale: boolean;
  reviews: Review[];
}

const IMG = {
  shoe: "https://images.unsplash.com/photo-1762943107238-a87f6f7bf6a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  football: "https://images.unsplash.com/photo-1575361204480-aadea25e6e68?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  gym: "https://images.unsplash.com/photo-1589955898954-9c8d4bb86823?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  running: "https://images.unsplash.com/photo-1769876457918-1871f21d63bc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  tennis: "https://images.unsplash.com/photo-1770681371006-fa3646d7e1b4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  basketball: "https://images.unsplash.com/photo-1549574984-508fb9671b2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  swimming: "https://images.unsplash.com/photo-1650112692344-09f6a6e4a03d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  jersey: "https://images.unsplash.com/photo-1659081469066-c88ca2dec240?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  yoga: "https://images.unsplash.com/photo-1646239646963-b0b9be56d6b5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  cycling: "https://images.unsplash.com/photo-1708105458243-143dcc24c308?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  bottle: "https://images.unsplash.com/photo-1767460073741-1bb4cd48a508?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
};

const mockReviews: Review[] = [
  {
    id: "r1",
    author: "Nguyễn Văn An",
    avatar: "NA",
    rating: 5,
    date: "20/03/2026",
    comment: "Sản phẩm chất lượng rất tốt, đúng với mô tả. Giao hàng nhanh, đóng gói cẩn thận. Sẽ mua lại lần sau!",
    verified: true,
  },
  {
    id: "r2",
    author: "Trần Thị Bích",
    avatar: "TB",
    rating: 4,
    date: "15/03/2026",
    comment: "Hàng đẹp, chất liệu tốt. Kích thước hơi nhỏ hơn thông thường, nên mua size lớn hơn 1 chút.",
    verified: true,
  },
  {
    id: "r3",
    author: "Lê Minh Tuấn",
    avatar: "LT",
    rating: 5,
    date: "10/03/2026",
    comment: "Mình đã dùng nhiều sản phẩm từ SportZone, chất lượng luôn đảm bảo. Rất hài lòng với mua hàng này.",
    verified: false,
  },
];

export const products: Product[] = [
  {
    id: "p1",
    name: "Giày Chạy Bộ ProRun X5",
    brand: "Nike",
    category: "Giày thể thao",
    sport: "Chạy bộ",
    price: 1850000,
    originalPrice: 2500000,
    image: IMG.shoe,
    images: [IMG.shoe, IMG.running, IMG.gym],
    rating: 4.8,
    reviewCount: 124,
    shortDescription: "Giày chạy bộ chuyên nghiệp với đệm khí tối ưu, phù hợp mọi địa hình",
    description: "Giày chạy bộ ProRun X5 được thiết kế cho những vận động viên nghiêm túc. Với công nghệ đệm khí AirCushion thế hệ mới, đôi giày mang lại sự êm ái và bảo vệ tối ưu cho mỗi bước chân. Đế ngoài được làm từ cao su tổng hợp bền bỉ, tăng độ bám đường trong mọi điều kiện thời tiết.",
    specs: {
      "Chất liệu mũi giày": "Lưới thoáng khí Flyknit",
      "Đế giữa": "Foam ReactX tùy chỉnh",
      "Đế ngoài": "Cao su tổng hợp bền bỉ",
      "Trọng lượng": "280g (size 42)",
      "Độ cao gót - mũi": "10mm",
      "Xuất xứ": "Việt Nam",
    },
    sizes: ["39", "40", "41", "42", "43", "44"],
    colors: [
      { name: "Xanh dương", hex: "#1D4ED8" },
      { name: "Đen", hex: "#111827" },
      { name: "Trắng", hex: "#F9FAFB" },
    ],
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isOnSale: true,
    reviews: mockReviews,
  },
  {
    id: "p2",
    name: "Bóng Đá Thi Đấu Chính Thức",
    brand: "Adidas",
    category: "Bóng",
    sport: "Bóng đá",
    price: 650000,
    originalPrice: 850000,
    image: IMG.football,
    images: [IMG.football, IMG.running],
    rating: 4.6,
    reviewCount: 89,
    shortDescription: "Bóng đá FIFA Quality Pro, chuẩn thi đấu quốc tế",
    description: "Bóng đá thi đấu chính thức đạt tiêu chuẩn FIFA Quality Pro. Được sản xuất từ da PU cao cấp với 32 tấm ghép chính xác, đảm bảo độ bay chuẩn và kiểm soát bóng tốt nhất trong mọi điều kiện thi đấu.",
    specs: {
      "Tiêu chuẩn": "FIFA Quality Pro",
      "Chất liệu": "Da PU cao cấp",
      "Số tấm ghép": "32",
      "Chu vi": "68-70cm",
      "Trọng lượng": "410-450g",
      "Xuất xứ": "Trung Quốc",
    },
    sizes: ["Size 4", "Size 5"],
    colors: [
      { name: "Trắng/Đen", hex: "#FFFFFF" },
      { name: "Xanh/Vàng", hex: "#F59E0B" },
    ],
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isOnSale: true,
    reviews: mockReviews,
  },
  {
    id: "p3",
    name: "Tạ Tay Cao Su 5kg",
    brand: "PowerMax",
    category: "Dụng cụ tập gym",
    sport: "Gym & Fitness",
    price: 320000,
    originalPrice: 320000,
    image: IMG.gym,
    images: [IMG.gym, IMG.yoga],
    rating: 4.5,
    reviewCount: 56,
    shortDescription: "Tạ tay bọc cao su chống trượt, an toàn và bền bỉ",
    description: "Tạ tay bọc cao su chất lượng cao với thiết kế ergonomic giúp nắm chắc và thoải mái. Lớp cao su bên ngoài giúp bảo vệ sàn nhà và giảm tiếng ồn khi tập luyện. Phù hợp cho cả người mới bắt đầu và vận động viên chuyên nghiệp.",
    specs: {
      "Trọng lượng": "5kg/quả",
      "Chất liệu": "Sắt đúc + Cao su",
      "Màu sắc": "Đen",
      "Độ bền": "Cao, không gỉ",
      "Xuất xứ": "Việt Nam",
    },
    sizes: ["2kg", "5kg", "8kg", "10kg"],
    colors: [{ name: "Đen", hex: "#111827" }],
    inStock: true,
    isNew: false,
    isBestSeller: false,
    isOnSale: false,
    reviews: mockReviews,
  },
  {
    id: "p4",
    name: "Áo Đấu Thể Thao DryFit Pro",
    brand: "SportZone",
    category: "Quần áo thể thao",
    sport: "Đa môn",
    price: 280000,
    originalPrice: 380000,
    image: IMG.jersey,
    images: [IMG.jersey, IMG.running],
    rating: 4.7,
    reviewCount: 203,
    shortDescription: "Áo thể thao công nghệ Dry-Fit, thoáng khí và thấm hút mồ hôi tốt",
    description: "Áo đấu thể thao DryFit Pro với công nghệ vải cao cấp giúp thấm hút mồ hôi nhanh chóng, giữ cho cơ thể luôn khô ráo và thoải mái trong suốt buổi tập. Thiết kế ôm sát nhưng không gò bó, phù hợp với nhiều môn thể thao khác nhau.",
    specs: {
      "Chất liệu": "100% Polyester Microfiber",
      "Công nghệ": "DryFit Pro",
      "Kiểu dáng": "Regular Fit",
      "Đặc tính": "Chống tia UV, Kháng khuẩn",
      "Bảo quản": "Giặt máy ≤ 40°C",
      "Xuất xứ": "Việt Nam",
    },
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "Xanh dương", hex: "#1D4ED8" },
      { name: "Đỏ", hex: "#DC2626" },
      { name: "Đen", hex: "#111827" },
      { name: "Trắng", hex: "#F9FAFB" },
    ],
    inStock: true,
    isNew: true,
    isBestSeller: false,
    isOnSale: true,
    reviews: mockReviews,
  },
  {
    id: "p5",
    name: "Vợt Cầu Lông Carbon Ultra",
    brand: "Yonex",
    category: "Vợt",
    sport: "Cầu lông",
    price: 1200000,
    originalPrice: 1500000,
    image: IMG.tennis,
    images: [IMG.tennis, IMG.running],
    rating: 4.9,
    reviewCount: 67,
    shortDescription: "Vợt cầu lông khung carbon cao cấp, nhẹ và cứng cáp",
    description: "Vợt cầu lông Carbon Ultra với khung làm từ sợi carbon T800 cao cấp, mang lại sức mạnh vượt trội và kiểm soát tốt. Cán vợt được thiết kế ergonomic giúp giảm rung lắc và chấn thương khi tập luyện kéo dài.",
    specs: {
      "Trọng lượng": "82g ± 2g",
      "Cân bằng": "Đầu vợt nhẹ",
      "Độ cứng": "Extra Stiff",
      "Chất liệu khung": "Carbon T800",
      "Căng dây": "22-26 lbs",
      "Xuất xứ": "Nhật Bản",
    },
    sizes: ["Mặc định"],
    colors: [
      { name: "Đỏ/Đen", hex: "#DC2626" },
      { name: "Xanh/Vàng", hex: "#1D4ED8" },
    ],
    inStock: true,
    isNew: true,
    isBestSeller: false,
    isOnSale: true,
    reviews: mockReviews,
  },
  {
    id: "p6",
    name: "Bóng Rổ Indoor/Outdoor",
    brand: "Spalding",
    category: "Bóng",
    sport: "Bóng rổ",
    price: 480000,
    originalPrice: 480000,
    image: IMG.basketball,
    images: [IMG.basketball],
    rating: 4.4,
    reviewCount: 42,
    shortDescription: "Bóng rổ dùng được cả trong nhà và ngoài trời",
    description: "Bóng rổ Indoor/Outdoor chất lượng cao với bề mặt composite da tổng hợp cho độ bám tốt. Phù hợp sử dụng trên cả sàn gỗ trong nhà và sân xi măng ngoài trời. Độ nảy chuẩn theo tiêu chuẩn FIBA.",
    specs: {
      "Size": "Size 7 (Chuẩn nam)",
      "Chất liệu": "Composite da tổng hợp",
      "Chu vi": "74.9-78cm",
      "Trọng lượng": "567-650g",
      "Phù hợp": "Trong nhà & Ngoài trời",
      "Xuất xứ": "Mỹ",
    },
    sizes: ["Size 5", "Size 6", "Size 7"],
    colors: [{ name: "Cam/Đen", hex: "#F97316" }],
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isOnSale: false,
    reviews: mockReviews,
  },
  {
    id: "p7",
    name: "Thảm Yoga TPE Cao Cấp 6mm",
    brand: "LifeFit",
    category: "Phụ kiện tập luyện",
    sport: "Yoga",
    price: 420000,
    originalPrice: 550000,
    image: IMG.yoga,
    images: [IMG.yoga, IMG.gym],
    rating: 4.7,
    reviewCount: 158,
    shortDescription: "Thảm yoga TPE chống trượt, thân thiện môi trường",
    description: "Thảm yoga TPE cao cấp dày 6mm cung cấp độ đệm hoàn hảo cho các khớp xương khi tập luyện. Bề mặt chống trượt kép (cả hai mặt) đảm bảo an toàn trong mọi tư thế yoga. Chất liệu TPE thân thiện với môi trường, không mùi hôi.",
    specs: {
      "Chất liệu": "TPE (Thermoplastic Elastomer)",
      "Kích thước": "183 x 61cm",
      "Độ dày": "6mm",
      "Trọng lượng": "1.5kg",
      "Đặc tính": "Chống trượt kép, Kháng khuẩn",
      "Xuất xứ": "Trung Quốc",
    },
    sizes: ["183x61cm", "183x68cm"],
    colors: [
      { name: "Xanh tím than", hex: "#6B21A8" },
      { name: "Xanh lá", hex: "#16A34A" },
      { name: "Hồng", hex: "#EC4899" },
    ],
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isOnSale: true,
    reviews: mockReviews,
  },
  {
    id: "p8",
    name: "Mũ Bơi Silicone Pro",
    brand: "Speedo",
    category: "Dụng cụ bơi lội",
    sport: "Bơi lội",
    price: 180000,
    originalPrice: 220000,
    image: IMG.swimming,
    images: [IMG.swimming],
    rating: 4.5,
    reviewCount: 34,
    shortDescription: "Mũ bơi silicone cao cấp, ôm khít và thoải mái",
    description: "Mũ bơi silicone Pro chất lượng cao với chất liệu silicone mềm mại, đàn hồi tốt giúp ôm khít phần đầu mà không gây đau. Thiết kế streamline giảm lực cản nước, tối ưu tốc độ bơi. Bền bỉ với cả nước muối và nước clo hồ bơi.",
    specs: {
      "Chất liệu": "100% Silicone cao cấp",
      "Kích thước": "Unisex (1 size)",
      "Đặc tính": "Chống UV, Bền với clo",
      "Độ dày": "1.5mm",
      "Xuất xứ": "Anh",
    },
    sizes: ["S/M", "L/XL"],
    colors: [
      { name: "Xanh dương", hex: "#1D4ED8" },
      { name: "Đỏ", hex: "#DC2626" },
      { name: "Đen", hex: "#111827" },
    ],
    inStock: true,
    isNew: false,
    isBestSeller: false,
    isOnSale: true,
    reviews: mockReviews,
  },
  {
    id: "p9",
    name: "Xe Đạp Thể Thao SpeedX 700C",
    brand: "Giant",
    category: "Xe đạp",
    sport: "Xe đạp",
    price: 8500000,
    originalPrice: 10000000,
    image: IMG.cycling,
    images: [IMG.cycling],
    rating: 4.8,
    reviewCount: 28,
    shortDescription: "Xe đạp thể thao khung nhôm nhẹ, 21 cấp số",
    description: "Xe đạp thể thao SpeedX 700C với khung nhôm 6061 siêu nhẹ và bền bỉ. Được trang bị hệ thống biến tốc Shimano 21 cấp số cho phép leo dốc và chạy tốc độ cao dễ dàng. Phanh đĩa hydraulic mang lại sự an toàn tối đa.",
    specs: {
      "Khung": "Nhôm 6061 Hydroformed",
      "Fork": "Carbon",
      "Biến tốc": "Shimano 21 cấp",
      "Phanh": "Đĩa Hydraulic",
      "Bánh xe": "700C x 25mm",
      "Trọng lượng": "8.5kg",
      "Xuất xứ": "Đài Loan",
    },
    sizes: ["S (165-175cm)", "M (175-185cm)", "L (185-195cm)"],
    colors: [
      { name: "Đen bóng", hex: "#111827" },
      { name: "Xanh carbon", hex: "#1E3A5F" },
    ],
    inStock: true,
    isNew: true,
    isBestSeller: false,
    isOnSale: true,
    reviews: mockReviews,
  },
  {
    id: "p10",
    name: "Bình Nước Thể Thao 1L",
    brand: "SportZone",
    category: "Phụ kiện",
    sport: "Đa môn",
    price: 150000,
    originalPrice: 150000,
    image: IMG.bottle,
    images: [IMG.bottle],
    rating: 4.3,
    reviewCount: 87,
    shortDescription: "Bình nước thể thao nhựa Tritan không BPA, 1 lít",
    description: "Bình nước thể thao 1L làm từ nhựa Tritan cao cấp không chứa BPA an toàn cho sức khỏe. Nắp bảo hiểm chống rò rỉ với nút bấm tiện lợi một tay. Thiết kế cầm vừa tay, phù hợp mang theo khi tập gym, chạy bộ hoặc leo núi.",
    specs: {
      "Dung tích": "1000ml",
      "Chất liệu": "Tritan BPA-Free",
      "Nhiệt độ": "0°C - 100°C",
      "Trọng lượng": "180g",
      "Kích thước": "Φ7.5 x H25cm",
      "Xuất xứ": "Việt Nam",
    },
    sizes: ["500ml", "750ml", "1000ml"],
    colors: [
      { name: "Xanh dương", hex: "#1D4ED8" },
      { name: "Xanh lá", hex: "#16A34A" },
      { name: "Đen", hex: "#111827" },
    ],
    inStock: true,
    isNew: false,
    isBestSeller: false,
    isOnSale: false,
    reviews: mockReviews,
  },
  {
    id: "p11",
    name: "Quần Short Gym Compression",
    brand: "Under Armour",
    category: "Quần áo thể thao",
    sport: "Gym & Fitness",
    price: 350000,
    originalPrice: 450000,
    image: IMG.running,
    images: [IMG.running, IMG.jersey],
    rating: 4.6,
    reviewCount: 95,
    shortDescription: "Quần short compression hỗ trợ cơ bắp, co giãn 4 chiều",
    description: "Quần short Gym Compression với vải co giãn 4 chiều đặc biệt hỗ trợ cơ bắp và giúp máu lưu thông tốt hơn. Công nghệ nén nhẹ giúp giảm mỏi cơ khi tập luyện cường độ cao. Thích hợp cho các bài tập gym, chạy bộ, cycling.",
    specs: {
      "Chất liệu": "83% Polyester, 17% Elastane",
      "Công nghệ": "HeatGear Compression",
      "Kiểu dáng": "Tight Fit",
      "Độ co giãn": "4 chiều",
      "Xuất xứ": "Hồng Kông",
    },
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Đen", hex: "#111827" },
      { name: "Xanh navy", hex: "#1E3A5F" },
    ],
    inStock: true,
    isNew: false,
    isBestSeller: false,
    isOnSale: true,
    reviews: mockReviews,
  },
  {
    id: "p12",
    name: "Găng Tay Boxing Pro",
    brand: "Everlast",
    category: "Dụng cụ boxing",
    sport: "Võ thuật",
    price: 520000,
    originalPrice: 680000,
    image: IMG.gym,
    images: [IMG.gym],
    rating: 4.5,
    reviewCount: 43,
    shortDescription: "Găng tay boxing da tổng hợp cao cấp, đệm dày bảo vệ tay",
    description: "Găng tay Boxing Pro làm từ da tổng hợp PU cao cấp với lớp đệm foam dày 3 lớp bảo vệ tay tối đa. Hệ thống dây băng cổ tay giúp cố định và bảo vệ khớp cổ tay. Phù hợp cho cả tập luyện và thi đấu hạng nhẹ.",
    specs: {
      "Chất liệu": "Da PU cao cấp",
      "Đệm lót": "Foam 3 lớp",
      "Khóa cổ tay": "Velcro chắc chắn",
      "Trọng lượng": "12oz, 14oz, 16oz",
      "Xuất xứ": "Pakistan",
    },
    sizes: ["10oz", "12oz", "14oz", "16oz"],
    colors: [
      { name: "Đỏ/Đen", hex: "#DC2626" },
      { name: "Đen", hex: "#111827" },
      { name: "Xanh/Đen", hex: "#1D4ED8" },
    ],
    inStock: true,
    isNew: true,
    isBestSeller: false,
    isOnSale: true,
    reviews: mockReviews,
  },
];

export const sportCategories = [
  { id: "all", name: "Tất cả", icon: "🏆" },
  { id: "Chạy bộ", name: "Chạy bộ", icon: "🏃" },
  { id: "Bóng đá", name: "Bóng đá", icon: "⚽" },
  { id: "Bóng rổ", name: "Bóng rổ", icon: "🏀" },
  { id: "Cầu lông", name: "Cầu lông", icon: "🏸" },
  { id: "Gym & Fitness", name: "Gym & Fitness", icon: "💪" },
  { id: "Bơi lội", name: "Bơi lội", icon: "🏊" },
  { id: "Xe đạp", name: "Xe đạp", icon: "🚴" },
  { id: "Yoga", name: "Yoga", icon: "🧘" },
  { id: "Võ thuật", name: "Võ thuật", icon: "🥊" },
  { id: "Đa môn", name: "Phụ kiện", icon: "🎽" },
];

export const brands = ["Nike", "Adidas", "Yonex", "Spalding", "Speedo", "Giant", "Under Armour", "Everlast", "PowerMax", "LifeFit", "SportZone"];

export function formatPrice(price: number): string {
  return price.toLocaleString("vi-VN") + "đ";
}
